#CAVM_SAI_URL = https://github.com/XPliant/OpenXPS/raw/c26aea6a7098936ab3692e148238d73fa8962585/SAI
LOCAL_PATH=/sonic

CAVM_XPNET_DEB = xp80-Pcie-Endpoint.deb
#$(CAVM_XPNET_DEB)_URL = $(CAVM_SAI_URL)/netdev/$(CAVM_XPNET_DEB)
$(CAVM_XPNET_DEB)_PATH = $(LOCAL_PATH)

#SONIC_ONLINE_DEBS += $(CAVM_XPNET_DEB)
SONIC_COPY_DEBS += $(CAVM_XPNET_DEB)
